FROM python:3.8

#Labels as key value pair
LABEL Maintainer="srinath"

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./model_inference.py"]